name: Scheduled Price Check

on:
  schedule:
    - cron: "0 23 * * *"  # 台灣早上 7 點（UTC 時區 +8 小時）
  workflow_dispatch:      # 也支援手動觸發

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price tracker
        run: python main.py
