name: Scheduled Price Check

on:
  schedule:
    - cron: '0 8 */3 * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2 libx264-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run price tracker
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python main.py
