name: Scheduled Price Check

on:
  schedule:
    - cron: '0 8 */3 * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2 \
            libxss1 \
            libxshmfence1 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libx11-xcb1 \
            libnss3 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libatspi2.0-0 \
            libxkbcommon0 \
            libdrm2 \
            libx264-163 \
            libasound2

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run price tracker
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python main.py
